### ISSUE TITLE
SA2BLVLs show up pure black ingame without vertex colors assigned

### ISSUE THREAD

**Issue by Shadowth117** [Justin113D/BlenderSA2Support#10]
Issue: 
.sa2blvl files exported from this addon show up pure black ingame when loaded without vertex colors assigned. Selecting meshes while in Vertex Paint mode appears to alleviate this, but is required for every mesh in the scene, which isn't particularly realistic.

Proposed Solution:
Automatically apply appropriate vertex colors upon export if none exist for a given mesh (I assume the default vertex paint assigned color is white)

Fuller context here in X-Hax Discord: https://discord.com/channels/446023672147345418/762646876188573698/991074443726053377

**Comment by J-N-R** [comment]
Would this also skip the need to SET "export colors" for every mesh in your level?

**Comment by Shadowth117** [comment]
> Would this also skip the need to SET "export colors" for every mesh in your level?

That's the idea really, is that that issue is a known flaw in the export handling. 
It's a bit ridiculous to expect to expect the user to do this for every mesh in what could be a massive scene regardless of if it's deemed to need coloring.

**Comment by Shadowth117** [comment]
At very worst, the current functionality could be an optional flag for a potential rare case in which this might work differently in the game. As is, it just seems harmful.

**Comment by J-N-R** [comment]
Update: Selecting a mesh in vertex paint mode creates a default "Color Attribute" in the 'Object Data Properties' menu, with the configuration being "Face Corner" and "Byte Color." It also creates an attribute in the "Color Attributes" menu, with the same configuration. I think the default color it chooses is black, but I could be wrong.

**Comment by ItsEasyActually** [comment]
Resolved in [81443e3](https://github.com/Justin113D/BlenderSASupport/commit/81443e36e6df25b0f01c0daea8d3c2e92312ceea).
