### ISSUE TITLE
Automatically create blank material for mesh in Quick Edit Menu (improvement)

### ISSUE THREAD

**Issue by J-N-R** [Justin113D/BlenderSA2Support#11]
Not a bug, but a suggestion. The Quick Edit Menu has the ability to set SA textures on any mesh, but you are still required to create a new material for every single mesh you want to texture for it to work. If the Quick Edit Menu created a blank material if no material was found when trying to set SA textures, you wouldn't need to manually create materials for new meshes, allowing texturing to be much quicker and easier.

**Comment by ItsEasyActually** [comment]
[Patched in 1ebe80a](https://github.com/Justin113D/BlenderSASupport/commit/1ebe80ad861f524f1dfd54f4f9da966295d140e6)

Added to current release.
