### ISSUE TITLE
Cant Import .SAtex file, only text list files .txt files

### ISSUE THREAD

**Issue by Foxeh89** [Justin113D/BlenderSA2Support#12]
was meaning to import some small objects into blender, such as the no parking sign from city escape.

while it allowed me to import a text list file, it wouldn't let me import the satex file as it doesn't recognize the .satex extension.

Returns the error "not a valid texture file" if i was to simply rename the .satex to .txt

**Comment by ItsEasyActually** [comment]
Patched in [df66d0a](https://github.com/Justin113D/BlenderSASupport/commit/df66d0aad763cabc1d1c8d64e8d1c7de328c7499).
