### ISSUE TITLE
Quick Edit Menu no longer removes/disables flags

### ISSUE THREAD

**Issue by J-N-R** [Justin113D/BlenderSA2Support#14]
Hi! So this ones a small one too, but basically something I've noticed is that while applying surface flags still works, unapplying them through the quick edit menu doesn't.

Normally to set collision, I'd select all meshes with "A" and then through quick edit, apply Solid & Visible (normally on by default, so you just enable landentry and hit set). Then, if there was anything special, like I had to remove visibility or collision from something, I would go to the quickedit menu, disable 'solid' and hit SET. But, for now, it looks like 'solid' stays, if it was previously set.

**Comment by ItsEasyActually** [comment]
You press Unset to disable flags from the Quick Menu. This feature has always functioned this way.

**Comment by J-N-R** [comment]
Oh lol my bad. Yea unset makes sense
