### ISSUE TITLE
can someone tell me why i get this error on export?

### ISSUE THREAD

**Issue by Jenssons** [Justin113D/BlenderSA2Support#16]
![image](https://user-images.githubusercontent.com/17034639/202051943-02f7d4b5-4ffe-4408-9cbd-0efb9c60ebac.png)

**Comment by ItsEasyActually** [comment]
You're attempting to export something that does not have the saObjflags attribute the addon adds. Only standard Objects and Bones have this attribute added to them.

**Comment by BladeZerlol** [comment]
how would someone fix it though?

**Comment by Aidenmash** [comment]
> You're attempting to export something that does not have the saObjflags attribute the addon adds. Only standard Objects and Bones have this attribute added to them.

Bro told us the issue, then leaves without explaining how to fix it.

**Comment by ItsEasyActually** [comment]
The issue was explained. You cannot export objects that do not contain the flags attribute. Use the **selected only** export option or **delete** anything that is not a **mesh, empty, or bone object** from the scene.
