### ISSUE TITLE
Unable to export

### ISSUE THREAD

**Issue by VaporwaveStudios** [Justin113D/BlenderSA2Support#2]
When I try to export in .sa2mdl format it doesn't  export it just pauses and resumes regular activity works fine in .sa1mdl format. here the files if it helps
[Soapy.zip](https://github.com/Justin113D/BlenderSASupport/files/3914307/Soapy.zip)
[The Only Altered Texture.zip](https://github.com/Justin113D/BlenderSASupport/files/3914315/The.Only.Altered.Texture.zip)

**Comment by Justin113D** [comment]
Besides the model being completely broken, it does export just fine in the newest version
