### ISSUE TITLE
Blue Channel + Alpha Incorrect When Exporting SA1Model

### ISSUE THREAD

**Issue by SkyNinja** [Justin113D/BlenderSA2Support#3]
When exporting a sa1model, the blue channel of the diffuse and specular colors along with the alpha are mixed. 
When diffuse is 178 178 178, specular is 255 255 255 and alpha is 0, the results after export are diffuse 178 178 255, specular 255 255 0 and alpha 178. The error seems to have existed since at least 1.1.3, and doesn't seem to occur when exporting .sa2model files.

**Comment by Justin113D** [comment]
fixed in 1.5.2
