### ISSUE TITLE
Error when trying to import textures to blender

### ISSUE THREAD

**Issue by BrendanScobal** [Justin113D/BlenderSA2Support#4]
![image](https://user-images.githubusercontent.com/38636334/86702048-33231600-bfd8-11ea-8e5e-ccb0de2dc6a9.png)
This appears when I use the "texture list specials" option to import and apply textures automatically. Both the tool and SATools are completely up to date.

edit: ItsEasyActually found out that the addon doesn't account for the dimensions at the end of each file in index.txt. Removing the dimensions makes it work

**Comment by ItsEasyActually** [comment]
Yeah, it's reading the index.txt as just gbix,name. All outputs from the texture editor will now be gbix,name,dimensions as PkR recently updated it to correct this issue.

**Comment by Justin113D** [comment]
Fixed in version 1.5.5
